### PR TITLE
fixes #7: Datatrans returns different response messages

### LINKED ISSUE #7: PostfinanceTransaction cannot be received
On successful PostFinance transactions the success path is called with the following parameter: `"responseMessage"=>"YellowPay transaction Ok"`

This is not accepted as _authorized_ here: https://github.com/simplificator/datatrans/blob/master/lib/datatrans/web/transaction/authorize.rb#L12

### PR DESCRIPTION
**Pull request by schmijos**
Depending on the payment method Datatrans returns different response messages.

### CODE REVIEW

**Comment by pascalbetz** [comment]
Thanks for the PR, we will review it ASAP.

**Comment by schmijos** [comment]
It's failing on ruby 1.8 but I've no clue why.

**Comment by denyago** [comment]
I've fixed Travis builds here https://github.com/simplificator/datatrans/pull/10

**Comment by andyundso** [comment]
hello @schmijos 

I wanted to ask if the fix you provided with [cbbd258](https://github.com/simplificator/datatrans/pull/8/commits/cbbd258223b36123beb41969ee02e035178f04dc) is still valid? If yes, we would cherry-pick the commit and add it to the gem.

**Comment by TatianaPan** [comment]
Replaced in #39

**Pull request closed without merging**
