### PR TITLE
Update datatrans hostnames

### PR DESCRIPTION
**Pull request by rgisiger**
Hi

Due to Datatrans asking to update the old hostnames, here is a PR to make those changes.

I have also updated the project dependencies.

### CODE REVIEW

**Comment by andyundso** [comment]
Hi @rgisiger :)

Thanks for the PR. As you might saw, we have been inactive on this repository for a while. However, we want to start again with proper maintenance for this gem.

We'll first setup a working pipeline again. I'll ping you once this is done so you can rebase your change.

**Comment by andyundso** [comment]
Hi @rgisiger 

Pipeline is ready :) Do you have time this week to rebase your branch (and exclude some commits like the version bump)? Otherwise we would take care of it and cherry-pick your commits.

**Comment by rgisiger** [comment]
Hi, yes I have time, I will have a look.

**Comment by rgisiger** [comment]
Rebase done @andyundso

**Review by andyundso — APPROVED** [review]
Looks good, thank you very much for the contribution.

**Pull request merged**
